In [1]:
import numpy as np
import pandas as pd

In [2]:
def read_input(path):
    """ Reads input file from passed path and returns as numpy array. No
    preprocessing is done. """
    with open(path, 'r') as f:
        data = np.array([l.strip() for l in f.readlines()])
    return data

### Day 1

#### Part 1

In [3]:
day_1_data = read_input("day_1/input.txt").astype(int)

In [4]:
def calc_positive_diff(arr):
    """ Given an array, count how many 'next values' are higher then the previous value. """
    return sum((arr[1:] - arr[:-1]) > 0)


def sum_by_window(arr, window_size=3):
    """ Slides a window_size sized window over an array and calculates the sums of the windows. """
    return pd.Series(arr).rolling(window=window_size).sum().dropna().values

In [5]:
calc_positive_diff(day_1_data)

1692

#### Part 2

In [6]:
# Calculate diff using sum of sliding window
calc_positive_diff(sum_by_window(day_1_data, window_size=3))

1724

### Day 2

#### Part 1

In [18]:
day_2_data = read_input("day_2/input.txt")

# Split lines into command and values and converts the values into integers
day_2_data = [[l[0], int(l[1])] for l in [line.split() for line in day_2_data]]

In [21]:
x_pos = 0
y_pos = 0

for command, value in day_2_data:
    if command.startswith('f'):
        x_pos += value
    elif command.startswith('d'):
        y_pos += value
    elif command.startswith('u'):
        y_pos -= value
        
x_pos * y_pos

1250395

#### Part 2

In [22]:
x_pos = 0
y_pos = 0
aim = 0

for command, value in day_2_data:
    if command.startswith('f'):
        x_pos += value
        y_pos += value * aim
    elif command.startswith('d'):
        aim += value
    elif command.startswith('u'):
        aim -= value
        
x_pos * y_pos

1451210346

In [23]:
# Numpy solution part 1
day_2_data = read_input("day_2/input.txt")
commands, values = zip(*[line.split() for line in day_2_data])
# Turn into arrays for slicing possibilities
commands = np.array(commands)
values = np.array(values).astype(int)

x_pos = values[commands == 'forward'].sum()
y_pos = values[commands == 'down'].sum() - values[commands == 'up'].sum()
x_pos * y_pos

1250395

### Day 3

In [118]:
def load_day_3_data():
    day_3_data = read_input("day_3/input.txt")
    day_3_data = [
        "00100",
        "11110",
        "10110",
        "10111",
        "10101",
        "01111",
        "00111",
        "11100",
        "10000",
        "11001",
        "00010",
        "01010"
    ]

    # Turn into numpy array, every bit on its own
    day_3_data = np.array([[int(bit) for bit in bytes_] for bytes_ in day_3_data])
    
    return day_3_data

#### Part 1

In [107]:
day_3_data = load_day_3_data()

In [108]:
# Gamma is most commit bit per 'column'
gamma = np.array([np.argmax(np.bincount(day_3_data[:, i])) for i in range(day_3_data.shape[1])])

# Epsilon is least common bit per column, so the opposite of the gamma
epsilon = 1 - np.array(gamma)

In [109]:
def byte_array_to_int(arr):
    return int(''.join(arr.astype(str)), base=2)

In [110]:
# Transform binary to number
gamma = byte_array_to_int(gamma)
epsilon = byte_array_to_int(epsilon)

In [111]:
# Answer is gamma times epsilon
gamma * epsilon

1458194

#### Part 2

In [144]:
day_3_data = load_day_3_data()

In [143]:
def day_3_part_2(data, filter_by='max'):
    assert filter_by in ['min', 'max']
    
    if filter_by == 'min':
        default = 0
        min_max_func = argmin
    else:
        default = 1
        min_max_func = argmax
    
    for idx in range(data.shape[1]):
        count = np.bincount(data[:, idx])
        if len(set(count)) > 1 or len(set(data[:, idx])) == 1:
            mcv = np.min_max_func(count)
        # Value if column contains the same amount of both values
        else:
            mcv = default

        # Remove rows where value of current index is not the most common value
        data = data[data[:, idx] == mcv]
        if data.shape[0] <= 1:
            break
            
    return data
    


In [ ]:
oxygen_rating = byte_array_to_int(day_3_part_2(day_3_data)[0])
co2_rating = byte_array_to_int(day_3_part_2(day_3_data)[0])

16

0
[5 7] 0
(12, 5)
[[0 0 1 0 0]
 [1 1 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 0 1 0 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 1 0]
 [0 1 0 1 0]]
1
[3 2] 1
(5, 5)
[[0 0 1 0 0]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 0]
 [0 1 0 1 0]]
2
[1 1] 0
(2, 5)
[[0 1 1 1 1]
 [0 1 0 1 0]]


array([[0, 1, 0, 1, 0]])